import Head from "next/head";
import { useState } from "react";
import Cookies from "universal-cookie";
import axios from "axios";

const initalFormState = {
    username: "",
    fullName: "",
    password: "",
    confirmPassword: "",
    phoneNumber: "",
    avatarURL: "",
};

const cookies = new Cookies();

export default function Auth() {
    const [isSignUp, setIsSignUp] = useState(false);
    const [form, setForm] = useState(initalFormState);
    const handleChange = (e) => {
        // console.log(e.target.name);
        // console.log(e.target.value);
        setForm({ ...form, [e.target.name]: e.target.value });
        // console.log({ form });
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        // console.log({ form });

        const { username, password, phoneNumber, avatarURL } = form;

        const URL = `http://localhost:5000/auth`;

        const {
            data: { token, userId, hashedPassword, fullName },
        } = await axios.post(`${URL}/${isSignUp ? "signup" : "login"}`, {
            username,
            password,
            fullName: form.fullName,
            phoneNumber,
            avatarURL,
        });

        cookies.set("token", token);
        cookies.set("username", username);
        cookies.set("fullName", fullName);
        cookies.set("userId", userId);

        if (isSignUp) {
            cookies.set("phoneNumber", phoneNumber);
            cookies.set("avatarURL", avatarURL);
            cookies.set("hashedPassword", hashedPassword);
        }

        window.location.reload();
    };

    const switchMode = () => {
        setIsSignUp((prevIsSignUp) => !prevIsSignUp);
    };
    return (
        <>
            <Head>
                <title>
                    {isSignUp
                        ? "Sign up to use Benji Chat"
                        : "Welcome Back! Log in to use Benji Chat"}
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <p>{isSignUp ? "Sign Up" : "Sign in"}</p>
            <form onSubmit={handleSubmit}>
                <div>
                    <label htmlFor="username">Username</label>
                    <input
                        required
                        type="text"
                        name="username"
                        placeholder="User name"
                        onChange={handleChange}
                    />
                </div>

                {isSignUp && (
                    <>
                        <div>
                            <label htmlFor="fullName">Full Name</label>
                            <input
                                required
                                type="text"
                                name="fullName"
                                placeholder="Full name"
                                onChange={handleChange}
                            />
                        </div>

                        <div>
                            <label htmlFor="phoneNumber">Phone number</label>
                            <input
                                required
                                type="text"
                                name="phoneNumber"
                                placeholder="Phone Number"
                                onChange={handleChange}
                            />
                        </div>
                        <div>
                            <label htmlFor="avatarURL">Avatar URL</label>
                            <input
                                required
                                type="text"
                                name="avatarURL"
                                placeholder="Avatar URL"
                                onChange={handleChange}
                            />
                        </div>
                    </>
                )}
                <div>
                    <label htmlFor="password">Password</label>
                    <input
                        required
                        type="password"
                        name="password"
                        placeholder="Password"
                        onChange={handleChange}
                    />
                </div>
                {isSignUp && (
                    <>
                        {" "}
                        <div>
                            <label htmlFor="confirmPassword">
                                Confirm Password
                            </label>
                            <input
                                required
                                type="password"
                                name="confirmPassword"
                                placeholder="Confirm Password"
                                onChange={handleChange}
                            />
                        </div>
                    </>
                )}
                <button type="submit">
                    {isSignUp ? "Sign Up" : "Sign in"}
                </button>
            </form>
            <div>
                <p>
                    {isSignUp
                        ? "Already have an account?"
                        : "Don't have an account?"}
                    <span onClick={switchMode}>
                        {" "}
                        {isSignUp ? "Sign in" : "Sign up"}
                    </span>
                </p>
            </div>
        </>
    );
}
