import dynamic from "next/dynamic";
import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { StreamChat } from "stream-chat";
import { Chat } from "stream-chat-react";
import Cookies from "universal-cookie";

import ChannelContainer from "@/components/ChannelContainer";
const DynamicChannelListContent = dynamic(() =>
    import("@/components/ChannelListContent")
);

import "stream-chat-react/dist/css/index.css";
const DynamicAuth = dynamic(() => import("@/components/Auth"));

const cookies = new Cookies();

const authToken = cookies.get("token");

const api_key = process.env.NEXT_PUBLIC_STREAM_API_KEY;
const client = StreamChat.getInstance(api_key);
if (authToken) {
    client.connectUser(
        {
            name: cookies.get("username"),
            fullName: cookies.get("fullName"),
            id: cookies.get("userId"),
            phoneNumber: cookies.get("phoneNumber"),
            image: cookies.get("avatarURL"),
            hashedPassword: cookies.get("hashedPassword"),
        },
        authToken
    );
}

export default function Home() {
    if (!authToken) {
        return (
            <>
                <DynamicAuth />
            </>
        );
    }

    return (
        <>
            <Head>
                <title>
                    {cookies.get("fullName") || cookies.get("username")}&apos;s
                    Benji Chat.
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-screen">
                <Chat client={client} theme="team light">
                    <div className="flex h-full">
                        <div className="lg:w-1/4">
                            <DynamicChannelListContent />
                        </div>
                        <div className="lg:w-3/4">
                            <ChannelContainer />
                        </div>
                    </div>
                </Chat>
            </div>
        </>
    );
}
