import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import Cookies from "universal-cookie";
import axios from "axios";

import H4 from "@material-tailwind/react/Heading4";

import { yupResolver } from "@hookform/resolvers/yup";
import * as Yup from "yup";

import { useForm, Controller } from "react-hook-form";

import { TextField } from "@mui/material";

import { Alert, Collapse, Button, CircularProgress } from "@mui/material";
import SendIcon from "@mui/icons-material/Send";

const cookies = new Cookies();

import { STREAM_API_URL } from "@/config/index";

export default function Login() {
    const router = useRouter();
    const [isErr, setIsErr] = useState(false);
    const [err, setErr] = useState("");
    const [isLoading, setIsLoading] = useState(false);

    const schema = Yup.object().shape({
        username: Yup.string().required("Username is a required field"),
        password: Yup.string().required("Please add a password"),
    });

    const defaultValues = {
        username: "",
        password: "",
    };

    const {
        register,
        handleSubmit,
        watch,
        formState: { errors },
        control,
    } = useForm({
        defaultValues,
        resolver: yupResolver(schema),
    });

    useEffect(() => {
        const subscription = watch((data) => {
            console.log(data);
            setErr("");
        });

        return () => {
            subscription.unsubscribe();
        };
    }, [watch]);

    const submitForm = async (form) => {
        console.log("submit form ", form);

        setIsLoading(true);

        try {
            // const { username } = form;
            const URL = `${STREAM_API_URL}/auth`;

            const {
                data: { token, fullName, userId, username, hashedPassword },
            } = await axios.post(`${URL}/login`, {
                username: form.username,
                password: form.password,
            });

            // console.log({ data });

            console.log({ token });
            // console.log({ username });
            console.log({ fullName });
            console.log({ userId });

            cookies.set("token", token);
            cookies.set("username", username);
            cookies.set("fullName", fullName);
            cookies.set("userId", userId);
            cookies.set("hashedPassword", hashedPassword);
            console.log({ hashedPassword });

            router.push("/");
            // setIsLoading(false);
        } catch (err) {
            setIsLoading(false);
            console.log({ err });
            setIsErr(true);
            if (err.response.data.message) {
                setErr(err.response.data.message);
            }
        }
    };

    return (
        <>
            <Head>
                <title>Hello! Sign in to use Benji Chat</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-screen bg-blue-100">
                <div className="flex h-full justify-center">
                    <div className="lg:w-1/4">
                        <div className="h-full flex items-center justify-center bg-blue-50">
                            <div className="flex justify-center items-center w-full">
                                <div className="w-11/12">
                                    <div className="bg-white p-12 rounded shadow w-full">
                                        <div className="text-center mb-6">
                                            <H4>Sign in</H4>
                                        </div>
                                        <form
                                            onSubmit={handleSubmit(submitForm)}
                                            className={`${isLoading} ? "opacity-75" : "" `}
                                        >
                                            {Object.keys(defaultValues).map(
                                                (objKey, i) => {
                                                    console.log({ objKey });
                                                    const result =
                                                        objKey.replace(
                                                            /([A-Z])/g,
                                                            " $1"
                                                        );
                                                    const finalResult =
                                                        result
                                                            .charAt(0)
                                                            .toUpperCase() +
                                                        result.slice(1);
                                                    return (
                                                        <Controller
                                                            key={i}
                                                            control={control}
                                                            render={() => (
                                                                <>
                                                                    <TextField
                                                                        {...register(
                                                                            objKey
                                                                        )}
                                                                        error={
                                                                            err ||
                                                                            errors[
                                                                                objKey
                                                                            ]
                                                                                ? true
                                                                                : false
                                                                        }
                                                                        autoFocus={
                                                                            i ===
                                                                            0
                                                                                ? true
                                                                                : false
                                                                        }
                                                                        className={`w-full bg-blue-50 rounded border-0 outline-none mb-2`}
                                                                        label={
                                                                            finalResult
                                                                        }
                                                                        placeholder={
                                                                            finalResult
                                                                        }
                                                                        helperText={
                                                                            errors[
                                                                                objKey
                                                                            ]
                                                                                ? errors[
                                                                                      objKey
                                                                                  ]
                                                                                      .message
                                                                                : ""
                                                                        }
                                                                        type={
                                                                            objKey ===
                                                                            "password"
                                                                                ? "password"
                                                                                : "text"
                                                                        }
                                                                        autoComplete="off"
                                                                        disabled={
                                                                            isLoading
                                                                                ? true
                                                                                : false
                                                                        }
                                                                        // variant="standard"
                                                                    />
                                                                </>
                                                            )}
                                                        />
                                                    );
                                                }
                                            )}

                                            <Button
                                                className="bg-blue-200"
                                                variant="contained"
                                                endIcon={
                                                    !isLoading ? (
                                                        <SendIcon />
                                                    ) : (
                                                        <CircularProgress
                                                            color="inherit"
                                                            size={20}
                                                        />
                                                    )
                                                }
                                                disabled={
                                                    isLoading ? true : false
                                                }
                                                type="submit"
                                            >
                                                Sign in
                                            </Button>
                                        </form>

                                        <Collapse in={isErr}>
                                            <Alert
                                                severity="error"
                                                onClick={() => setIsErr(false)}
                                            >
                                                {err}
                                            </Alert>
                                        </Collapse>

                                        <div>
                                            {`Don't yet have an account? `}
                                            <Link href="/register/">
                                                <a>Register here</a>
                                            </Link>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}
